---
- hosts: localhost
  connection: local
  gather_facts: no


  vars:
    userId: "alertmanager"
    groupId: "alertmanager"
    version: "0.17.0"

  tasks:
    - name: Creating alertmanager user group
      group: name="{{groupId}}"
      become: true

    - name: Creating alertmanager user
      user:
        name: "{{userId}}"
        group: "{{groupId}}"
        system: yes
        shell: "/sbin/nologin"
        comment: "{{userId}} nologin User"
        createhome: "no"
        state: present

    - name: Download alertmanager
      unarchive:
        src: "https://github.com/prometheus/alertmanager/releases/download/v{{ version }}/alertmanager-{{ version }}.linux-amd64.tar.gz"
        dest: /tmp/
        remote_src: yes

    - name: Copy alertmanager executable to bin
      copy:
        src: "/tmp/alertmanager-{{ version }}.linux-amd64/alertmanager"
        dest: "/usr/local/bin/alertmanager"
        owner: "{{userId}}"
        group: "{{groupId}}"
        remote_src: yes
        mode: 0755

    - name: Delete alertmanager tmp folder
      file:
        path: '/tmp/alertmanager-{{ version }}.linux-amd64'
        state: absent
    - name: Copy config file
      copy:
        src: /tmp/alertmanager.yml
        dest: /etc/alertmanager/alertmanager.yml

    - name: Copy systemd init file
      template:
        src: /tmp/alertmanager.service
        dest: /etc/systemd/system/prometheus.service
#      notify:


    - name: Start alertmanager service
      service:
        name: alertmanager
        state: started
        enabled: yes

    - name: Check if alertmanager is accessible
      uri:
        url: http://localhost:9093
        method: GET
        status_code: 200
